#ifndef ENUMS_H
#define ENUMS_H

enum Type { INT32, INT64, CHAR, VOID};
enum Opbinaire { EQUAL, MULT, DIV, PLUS, MINUS, UPPERTHAN, UPPEROREQUAL, LOWERTHAN, LOWEROREQUAL, PLUSEQUAL, MINUSEQUAL, DIVEQUAL, MULTEQUAL, COMMA};
enum Opunaire { MINUSMINUS, PLUSPLUS, NO, NEG};
enum TypeControle {IF, WHILE, FOR};

#endif
