enum Type { INT32, INT64, CHAR, VOID};
enum Opbinaire { EQUAL, MULT, DIV, PLUS, MINUS, UPPERTHAN, UPPEROREQUAL, LOWERTHAN, LOWEROREQUAL, PLUSEQUAL, MINUSEQUAL, DIVEQUAL, MULTEQUAL, COMMA};
enum Opunaire { MINUSMINUS, PLUSPLUS, NO, MINUS};
enum TypeControle {IF, WHILE, FOR};
