#ifndef ENUMS_H
#define ENUMS_H

enum Type { INT32_T, INT64_T, CHAR_T, INT32TAB_T, INT64TAB_T, CHARTAB_T, VOID_T, CONSTVAL_T};
enum Opbinaire { EQUAL_OB, MULT_OB, DIV_OB, PLUS_OB, MINUS_OB, UPPERTHAN_OB, UPPEROREQUAL_OB, LOWERTHAN_OB, LOWEROREQUAL_OB, PLUSEQUAL_OB, MINUSEQUAL_OB, DIVEQUAL_OB, MULTEQUAL_OB, DOUBLEEQUAL_OB, MODULO_OB, NOTEQUAL_OB, OR_OB, AND_OB};
enum Opunaire { DECR_OU, INCR_OU, NOT_OU, NEG_OU};
enum TypeControle {IF_TC, WHILE_TC, FOR_TC};
enum TypeContenu { _LIGNE, _DECLARATION, _RETURN, _EXPR, _OPUNAIRE, _OPBINAIRE, _AFFECTATION, _VAR, _VARS, _VARTAB, _APPELFONCT, _BLOCCONTROLE, _BLOCIF, _BLOCFOR, _BLOCWHILE };

#endif
